### ISSUE TITLE
Possible outdated information

### ISSUE THREAD

**Issue by Mihaiii** [allenai/CommonGen-Eval#2]
Awesome repo! I'm happy there is something like it.

I noticed the [website that hosts the leaderboard](https://inklab.usc.edu/CommonGen/leaderboard.html) has a section for submitting a new model to the leaderboard that involves sending the results on email.

I'm assuming that that info is outdated (the format of the file offered as example also doesn't match with what is generated) and that in order to submit a new model to the leaderboard all we have to do is make a PR in this repo instead, like it's mentioned in this repo's readme.md file.

Please let me know if my assumption is incorrect.

**Comment by yuchenlin** [comment]
Hi Mihai, thanks a lot for the first issue! Yes, the previous submission guideline is outdated, and I have removed it now.
